### ISSUE TITLE
Polybar missing parameter 

### ISSUE THREAD

**Issue by samerickson** [IbrahimButt/Direwolf-Arch-Rice#6]
I get:
```
error: Disabling module "cpu" (reason: Missing parameter "module/cpu.type")
error: Disabling module "memory" (reason: Missing parameter "module/memory.type"))
```

**Comment by ibrahimbutt** [comment]
Hey @samerickson, inside the `.config/polybar/config` CPU and Memory modules are not used.  With the information given, I'm assuming you edited the file to include them yourself? 

You should take a look at the [Polybar repo](https://github.com/jaagr/polybar) to make sure you properly updated `config`.

**Comment by tsukijin** [comment]
> CPU and Memory modules are not used. 

Your polybar config enables the cpu and memory modules on the right side of polybar, but since they aren't enabled they display that error. 
https://github.com/ibrahimbutt/direwolf-arch-rice/blob/f2c51cdb2a4b85855b58947e769b5a0f1d7a7d3f/.config/polybar/config#L31

**Comment by benniemosher** [comment]
So, how do we enable them? My file has that in it, and I would like to see both of them.  Is there something I need to install?
